version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo:dev
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend/Task Tracker
      dockerfile: Dockerfile
    container_name: task-tracker-backend:dev
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DATABASE_URL=mongodb://mongo:27017/task-tracker
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend/Ts-react
      dockerfile: Dockerfile
    container_name: task-tracker-frontend:dev
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:3001
    depends_on:
      - backend

volumes:
  mongo-data:
