apiVersion: v1
kind: Service
metadata:
  labels:
    app: task-tracker-frontend
  name: task-frontend
  namespace: task-tracker
spec:
  ports:
  - nodePort: 31111
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: task-tracker-frontend
  sessionAffinity: None
  type: NodePort
