apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker-frontend
  namespace: task-tracker
  labels:
    app: task-tracker-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-tracker-frontend
  template:
    metadata:
      labels:
        app: task-tracker-frontend
    spec:
      containers:
      - name: task-frontend
        image: hadensmith/task-tracker-frontend:v5
        ports:
        - containerPort: 80

