apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongodb-pv
  nodeAffinity:
    required:
      nodeSelectorTerms: 
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - node01
