apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: task-tracker
  labels:
    app: mongo  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      nodeSelector: 
        kubernetes.io/hostname: node01
      containers:
      - name: mongo
        image: mongo:4.4
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: mongo-storage
            mountPath: /data/db
      volumes: 
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
